name: chatx
description: ChatX - Modern Messenger App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  uuid: ^4.3.3
  timeago: ^3.6.1

  # 🛠️ حل مشاكل الـ Build والـ Import
  file_picker: ^8.0.0    # عشان تختار ملفات الـ Zip بتاعت الاستيكرات والإيموجي
  archive: ^3.6.1        # المكتبة اللي فكت الضغط وسببت الايرور الأخير
  path_provider: ^2.1.2  # ضرورية جداً عشان تحفظ الإيموجي في ذاكرة الموبايل بعد فكها

  # ✨ ميزات الـ Premium & Modern UI
  lottie: ^3.1.0         # عشان الرموز المتحركة (Animated Emojis) اللي هتجنن الناس
  path: ^1.9.0           # بتساعد في تنظيم مسارات الملفات جوه السيستم

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/lottie/   # فك الكومنت لو هتحط ملفات Lottie محليا
